version = 1

[[mods]]
modid = "examplemod"
display_name = "Example Mod"
enabled_formats = ["patchouli"]

[[mods]]
modid = "apprenticecodex"
display_name = "Apprentice's Codex"
enabled_formats = ["patchouli"]
